export const sidemenu=[{
    label:"Home",
    to:'/'
},
{
    label:"Details",
children:[{
    label:"Location"
}]
},
{
    label:'Settings',
    children:[
        {
            label:'Account'
        },
        {
            label:'Security',
            children:[{
                label:'Login'
            },
            {
                label:'Register'
            }
        ]
        }
    ]
}
]